'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { GoogleSignIn } from '../components/GoogleSignIn';

type Admin={email:string;added_at:string};
export default function Admin(){
  const [credential,setCredential]=useState(''),[platformAdmin,setPlatformAdmin]=useState<boolean|null>(null),[date,setDate]=useState(''),[startTime,setStart]=useState('12:00'),[endTime,setEnd]=useState('14:00'),[capacity,setCapacity]=useState(10),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[admins,setAdmins]=useState<Admin[]>([]),[newAdmin,setNewAdmin]=useState('');
  const authHeaders=useCallback(():Record<string,string>=>credential?{authorization:`Bearer ${credential}`}:{},[credential]);
  const loadAdmins=useCallback(async()=>{const r=await fetch('/api/admin/admins',{headers:authHeaders()});if(r.ok){const d=await r.json() as {admins:Admin[]};setAdmins(d.admins);}},[authHeaders]);
  useEffect(()=>{fetch('/api/admin/slots').then(r=>r.json() as Promise<{isChef:boolean}>).then(d=>setPlatformAdmin(d.isChef)).catch(()=>setPlatformAdmin(false));},[]);
  const authorized=platformAdmin||Boolean(credential);
  useEffect(()=>{if(authorized)loadAdmins();},[authorized,loadAdmins]);
  async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');const timezoneOffset=new Date(`${date}T${startTime}:00`).getTimezoneOffset();const r=await fetch('/api/admin/slots',{method:'POST',headers:{'content-type':'application/json',...authHeaders()},body:JSON.stringify({date,startTime,endTime,capacity,timezoneOffset})});const d=await r.json() as {created?:number;error?:string};setMessage(r.ok?`${d.created} משבצות של חצי שעה פתוחות כעת להזמנה.`:d.error||'לא הצלחנו לפתוח את המועדים');setBusy(false);}
  async function addAdmin(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/admins',{method:'POST',headers:{'content-type':'application/json',...authHeaders()},body:JSON.stringify({email:newAdmin})});const d=await r.json() as {error?:string};if(!r.ok){setMessage(d.error||'לא הצלחנו להוסיף מנהל');return;}setNewAdmin('');setMessage('המנהל נוסף בהצלחה.');await loadAdmins();}
  async function removeAdmin(email:string){const r=await fetch('/api/admin/admins',{method:'DELETE',headers:{'content-type':'application/json',...authHeaders()},body:JSON.stringify({email})});const d=await r.json() as {error?:string};if(!r.ok){setMessage(d.error||'לא הצלחנו להסיר מנהל');return;}await loadAdmins();}
  return <main className="admin-page"><nav className="nav"><Link className="brand" href="/"><span className="brand-mark">七</span><span>ראמן בעבודת יד</span></Link><Link className="chef-link" href="/">לתצוגת אורחים</Link></nav><section className="admin-wrap"><div className="admin-heading"><p className="eyebrow">הדלפק של השף</p><h1>פותחים<br/>מועד חדש.</h1><p>בחרו תאריך וטווח שעות. המערכת תחלק אותו אוטומטית למשבצות של 30 דקות ותעצור הזמנות כשהמכסה מתמלאת.</p></div><div className="admin-column"><div className="admin-card">{platformAdmin===null?<p className="empty-copy">בודק הרשאת מנהל…</p>:!authorized?<><p className="kicker">כניסת מנהלים</p><h2>התחברות עם Google</h2><p className="empty-copy">מנהלים מורשים יכולים להתחבר עם חשבון Gmail ולפתוח מועדים.</p><GoogleSignIn onCredential={setCredential}/></>:<form onSubmit={create}><p className="kicker">ארוחה חדשה</p><label>תאריך<input required type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><div className="form-row"><label>משעה<input required type="time" step="1800" value={startTime} onChange={e=>setStart(e.target.value)}/></label><label>עד שעה<input required type="time" step="1800" value={endTime} onChange={e=>setEnd(e.target.value)}/></label></div><label>מספר אורחים בכל 30 דקות<input required type="number" min="1" max="100" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><button className="reserve" disabled={busy}>{busy?'פותח מועדים…':'פתיחת הזמנות'}<span>←</span></button></form>}</div>{authorized&&<div className="admin-card admins-card"><p className="kicker">מנהלי האתר</p><h2>הרשאות Gmail</h2><form className="add-admin" onSubmit={addAdmin}><label>הוספת מנהל לפי אימייל<input required type="email" placeholder="name@gmail.com" value={newAdmin} onChange={e=>setNewAdmin(e.target.value)}/></label><button type="submit">הוספה</button></form><div className="admin-list">{admins.map(a=><div key={a.email}><span>{a.email}</span><button type="button" onClick={()=>removeAdmin(a.email)} aria-label={`הסרת ${a.email}`}>הסרה</button></div>)}</div></div>}{message&&<p className="form-message" role="status">{message}</p>}</div></section></main>;
}
