'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { GoogleSignIn } from '../components/GoogleSignIn';

export default function Admin(){
  const [credential,setCredential]=useState(''),[platformAdmin,setPlatformAdmin]=useState<boolean|null>(null),[date,setDate]=useState(''),[startTime,setStart]=useState('12:00'),[endTime,setEnd]=useState('14:00'),[capacity,setCapacity]=useState(10),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{fetch('/api/admin/slots').then(r=>r.json() as Promise<{isChef:boolean}>).then(d=>setPlatformAdmin(d.isChef)).catch(()=>setPlatformAdmin(false));},[]);
  const authorized=platformAdmin||Boolean(credential);
  async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');const timezoneOffset=new Date(`${date}T${startTime}:00`).getTimezoneOffset();const r=await fetch('/api/admin/slots',{method:'POST',headers:{'content-type':'application/json',...(credential?{authorization:`Bearer ${credential}`}:{})},body:JSON.stringify({date,startTime,endTime,capacity,timezoneOffset})});const d=await r.json() as {created?:number;error?:string};setMessage(r.ok?`${d.created} משבצות של חצי שעה פתוחות כעת להזמנה.`:d.error||'לא הצלחנו לפתוח את המועדים');setBusy(false);}
  return <main className="admin-page"><nav className="nav"><Link className="brand" href="/"><span className="brand-mark">七</span><span>DOWN TOWN RAMEN</span></Link><Link className="chef-link" href="/">תצוגת אורחים</Link></nav><section className="admin-wrap"><div className="admin-heading"><p className="eyebrow">הדלפק של השף</p><h1>פותחים<br/>מועד חדש.</h1><p>בחרו תאריך וטווח שעות. המערכת תחלק אותו אוטומטית למשבצות של 30 דקות ותעצור הזמנות כשהמכסה מתמלאת.</p></div><div className="admin-card">{platformAdmin===null?<p className="empty-copy">בודק הרשאת מנהל…</p>:!authorized?<><p className="kicker">גישה פרטית</p><h2>כניסה כמנהל</h2><p className="empty-copy">רק חשבון המנהל המוגדר יכול לפתוח מועדים להזמנה.</p><GoogleSignIn onCredential={setCredential}/></>:<form onSubmit={create}><p className="kicker">ארוחה חדשה</p><label>תאריך<input required type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><div className="form-row"><label>משעה<input required type="time" step="1800" value={startTime} onChange={e=>setStart(e.target.value)}/></label><label>עד שעה<input required type="time" step="1800" value={endTime} onChange={e=>setEnd(e.target.value)}/></label></div><label>מספר אורחים בכל 30 דקות<input required type="number" min="1" max="100" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><button className="reserve" disabled={busy}>{busy?'פותח מועדים…':'פתיחת הזמנות'}<span>←</span></button>{message&&<p className="form-message" role="status">{message}</p>}</form>}</div></section></main>;
}
